export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const FETCH_DELETED_EMPLOYEES = 'FETCH_DELETED_EMPLOYEES';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const SOFT_DELETE_EMPLOYEE = 'SOFT_DELETE_EMPLOYEE';
